schemas: introduce assigned-clock-rates-u64
devicetree-org/dt-schema pull request #140
Opened 2024-06-21 12:26 UTC by MrVan

To support rates that exceeds UINT32_MAX, introduce assigned-clock-rates-u64

2024-06-26 01:15 UTC, MrVan commented
@robherring  do you have time to give a look on this? Thanks.

2024-06-26 13:17 UTC, robherring requested changes

2024-06-26 13:17 UTC, robherring commented on dtschema/schemas/clock/clock.yaml
> +    $ref: /schemas/types.yaml#/definitions/uint32-array
Should be uint64-array

2024-06-27 02:22 UTC, MrVan commented on dtschema/schemas/clock/clock.yaml
> +    $ref: /schemas/types.yaml#/definitions/uint32-array
Updated to uint64-array

2024-06-27 06:42 UTC, krzk commented
> @robherring do you have time to give a look on this? Thanks.

BTW, before pinging someone you could answer to existing review. You do not need two reviewers telling you that 32-bit would not work. One reviewer is enough...

2024-06-27 06:47 UTC, krzk approved these changes

2024-06-27 07:29 UTC, MrVan commented
> > @robherring do you have time to give a look on this? Thanks.
> 
> BTW, before pinging someone you could answer to existing review. You do not need two reviewers telling you that 32-bit would not work. One reviewer is enough...

@krzk sorry, I not see comment in this page before I asked Rob to comment. From go through this page, I only see Rob has a comment several hours before.

2024-06-27 07:33 UTC, MrVan commented on dtschema/schemas/clock/clock.yaml
> +    $ref: /schemas/types.yaml#/definitions/uint32-array
`
assigned-clocks =<&scmi_clk IMX95_CLK_HSIOPLL_VCO>;

assigned-clock-rates-u64 = <0x1 0x1e1a3000>;
`


The linux patch: https://lore.kernel.org/all/20240621-clk-u64-v1-0-d28a611b2621@nxp.com/

2024-06-27 07:48 UTC, MrVan commented
> > > @robherring do you have time to give a look on this? Thanks.
> > 
> > 
> > BTW, before pinging someone you could answer to existing review. You do not need two reviewers telling you that 32-bit would not work. One reviewer is enough...
> 
> @krzk sorry, I not see comment in this page before I asked Rob to comment. From go through this page, I only see Rob has a comment several hours before.

My gmail shows
![image](https://github.com/devicetree-org/dt-schema/assets/4230248/06784753-722a-464c-a221-c20411794646)

2024-06-27 07:55 UTC, krzk commented on dtschema/schemas/clock/clock.yaml
> +    $ref: /schemas/types.yaml#/definitions/uint32-array
So you can see it is not u32 value... Never mind.

2024-06-27 13:06 UTC, merged